# **IMPUTER**

# SIMPLE IMPUTER

In [7]:
from sklearn.impute import SimpleImputer
import pandas as pd


simple =SimpleImputer(strategy="mean")
data = pd.read_csv(r"D:\University\University Work\Semestor 4\Programming of ai\LAB\Datasets\titanic_toy.csv")

In [8]:
imputed_data = pd.DataFrame(simple.fit_transform(data))  # converting the data and the simple imputer to the data given

In [9]:
imputed_data

             0          1    2    3
0    22.000000   7.250000  1.0  0.0
1    38.000000  71.283300  1.0  1.0
2    26.000000   7.925000  0.0  1.0
3    35.000000  53.100000  1.0  1.0
4    35.000000   8.050000  0.0  0.0
..         ...        ...  ...  ...
886  27.000000  13.000000  0.0  0.0
887  19.000000  30.000000  0.0  1.0
888  29.699118  23.450000  3.0  0.0
889  26.000000  32.279338  0.0  1.0
890  32.000000   7.750000  0.0  0.0

[891 rows x 4 columns]

In [10]:
imputed_data.isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

# KNN IMPUTER

In [11]:
from sklearn.impute import KNNImputer
import pandas as pd


KNNimputer = KNNImputer(n_neighbors=2)
KNN_IMPUTED_DATA = pd.DataFrame(KNNimputer.fit_transform(data))

KNN_IMPUTED_DATA.head()

      0        1    2    3
0  22.0   7.2500  1.0  0.0
1  38.0  71.2833  1.0  1.0
2  26.0   7.9250  0.0  1.0
3  35.0  53.1000  1.0  1.0
4  35.0   8.0500  0.0  0.0