# **NEAR MISS CODE Version-1**

In [1]:
import numpy as np
import pandas as pd
from collections import Counter
from imblearn.under_sampling import NearMiss

In [2]:
x = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6],[6,9]])
y = np.array([0, 0, 1, 1, 1, 1])

Counter(y)

Counter({np.int64(1): 4, np.int64(0): 2})

In [20]:
nearmiss = NearMiss(n_neighbors=2)

x_nm ,y_nm   = nearmiss.fit_resample(x,y)


x = pd.DataFrame(x_nm, columns=['x1', 'x2'])
y = pd.Series(y_nm, name='target')

data = pd.concat([x, y], axis=1)

In [21]:
data

   x1  x2  target
0   1   2       0
1   2   3       0
2   3   4       1
3   4   5       1

In [22]:
nearmiss = NearMiss(n_neighbors=2, version=2)

x_nm ,y_nm   = nearmiss.fit_resample(x,y)


x = pd.DataFrame(x_nm, columns=['x1', 'x2'])
y = pd.Series(y_nm, name='target')

data = pd.concat([x, y], axis=1)
data

   x1  x2  target
0   1   2       0
1   2   3       0
2   3   4       1
3   4   5       1

In [3]:
nearmiss = NearMiss(n_neighbors=2, version=3)

x_nm ,y_nm   = nearmiss.fit_resample(x,y)


x = pd.DataFrame(x_nm, columns=['x1', 'x2'])
y = pd.Series(y_nm, name='target')

data = pd.concat([x, y], axis=1)
data

   x1  x2  target
0   1   2       0
1   2   3       0
2   5   6       1
3   4   5       1